### ISSUE TITLE
Implementar el Item del Menú Declarme en Bancarrota

### ISSUE THREAD

**Issue by pablomoreno87** [ale-bos/tsb-monopoly#13]
Implementar la funcionalidad del botón del menu Acciones para el caso de que el jugador quiera declararse en bancarrota.

**Comment by alebostico** [comment]
Crear un método `Jugador.pasarABancarrota();` que haga lo siguiente:
1. Recorrer las propiedades y vender los edificios que puedan tener.
2. Pasar todas las propiedades al banco y deshipotecar las que estén hipotecadas.
3. Poner al jugador en estado de bancarrota=true.
4. No mostrar al jugador en el listado de jugadores ni hacerlo jugar nuevamente.
5. Si el jugador es Humano, desconectar la sesión.

**Comment by alebostico** [comment]
Listo. Ya está terminado.
