### ISSUE TITLE
Tarjeta null

### ISSUE THREAD

**Issue by pablomoreno87** [ale-bos/tsb-monopoly#20]
Cuando el jugador virtual saca una tarjeta de la suerte en el mensaje muestra null. Verificar funcionalidad.
Stack Trace:
Log[INFO ](21:50) bota: Avanzó 7 casilleros. Se encuentra en el casillero SUERTE.
Log[INFO ] Jugador: bota ~~~> acción : TARJETA_SUERTE ~~~> Mensaje Saca una tarjeta de la suerte..
Log[INFO ](21:50) bota: Saca una tarjeta de la suerte.
Log[INFO ] Jugador: bota ~~~> acción : PAGAR_POR_CASA_HOTEL ~~~> Mensaje null ~~~> Objetivo: LA INSPECCIÓN DE LA CALLE TE OBLIGA&#10;A REPARACIONES.&#10;PAGA 40 € POR CADA CASA.&#10;PAGA 115 € POR HOTEL..
Log[INFO ](21:50) bota: null
Log[INFO ](21:50) bota: Finalizó su turno.

**Comment by alebostico** [comment]
Listo. Corregido en 031c97beb8b9106a91f925dba99b5baa68e66500
